# Generated by Django 4.2.7 on 2023-11-07 15:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('classmates', '0002_classmate_address_classmate_date_of_birth_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='classmate',
            name='date_of_birth',
        ),
    ]
